dist: xenial
language: clojure
lein: 2.8.3
cache:
  directories:
    - $HOME/.m2
    - /usr/local
install:
  - sudo ./scripts/install-ci-deps /usr/local
  - lumo --version
script:
  - ./scripts/test-jvm
  - ./scripts/test-lumo
jdk:
  - openjdk8
  - openjdk11
  - openjdk-ea
matrix:
  fast_finish: true
  allow_failures:
    - jdk: openjdk-ea
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/14f0f7b4d5b20a70d032
    on_success: change
    on_failure: change
    on_start: never
